name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main  # 只在 main 分支同步

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full Git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 取消 shallow clone，获取完整历史

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/amber6hua/newwv2b.git
          git push --mirror gitlab
